language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/toutatice.git"
  # REGISTRY_TOKEN
  secure: J2c/4MASf6u4fK/XMJg8NfLn2ge4ojmVckawIXhUVAnmsfG/IQ3fd5Eb4wsgSlj8CvsENK4ZDgkV8/EIhvnaKa+wM1i46L3UjUP+DACtYr321Z97dsSxLx1R8fuQ/btc8F1xUUvnJ5FrZo0BwLo+lo5p8jiYz1kFvwwr2PIz27spz+OOaP30KqiYFDHFtb2sAUJjU2hzD5HtzVgUkLepav0817wC6wYwF9yWg+V3Gr76ug4Y+sBAVwGkf2AgM7NyO7qdqsZyVWv9fKBj4FzQhqU3o/aZT/LAs4x9EgxYaDRk78AOEsWrpY0buKzK+nJ3fb/TRnkFW+nv6ZLWDO1axlFydFzHtx0ieuOoKO2dvcYrOuYUtbMQbkTWBmt4P/cYkmZYoRHLx55dRL1LTDm+RsEbA0MUmMN0ri7TJ4BwM9/BbMOaqTlW96K9pouwf7wn40NfksQ0lVD4fuPtTybN6/zipsQYKCrxdIQ4lCryopB2+UshGwkEX0MmenSiWZkVy9AvCWH6ZiVtvoBuROUKDEpsed0MvOusSjDBrw35W6DtE8taxY3JY+x/2131/UvHRHiyG0PlTcdieRFNLrOteGndIYiHDoSKo0F6rreFyTB3u9tyvrOSHBmREbBZVuxb4Gj33xyQlL0SRFqX8KNryMDPyqCJnJUwh3YkrukAbos=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_5e5aaf50d9bf_key -iv $encrypted_5e5aaf50d9bf_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
