language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/toutatice.git"
  # REGISTRY_TOKEN
  secure: Dc7bO1BQwhiVeOvBLeJ0idQoQ6tJhDJg+bvGXydYr938HIz+XqEYNjPX8JbW1ucvBcvzA6LWs0eeAhrIfBwlTiIx7cx8YBI1B1kTZvXMkJHe/jfmd5H43f/XRc3JRZrVXGj8Vm3rY/+Qh+FH5fa2hF4KVwuMRknfYZV30tNfxUyWj1zxduxVcE/2vGt87C5AlarycEzCBTV4O6VGfOkW3i9eqz6maA2/2j4cmbpVocgkd2VuAbq27PVYONJW5ftTwats4cL2dPCVM9vAFs/cnZ4G2bg1dUJjQ3AGByTBq81sCrCRFoqVQ9FeI2ZXkkk606rzWekaKFdMYdlIPJ9uJqMlJ3wscDfIc3P/PiadzBhu9FAa0Ov+taNfrMaZdsU+5JDdDGCREnDCovyIoXQDgtyWaXAipYfzwM7Cjh4yX3+kCDmqDAVvTuktM42eHwNtjzf3r18oKXOvsE6RQX/1xMsmsUZcd7bWw1yWGgawxvnE5tx2ss4z8CA0RNaSef9EQU8xf4D3ewC+OkWNyAgUxV2WZjG5mI6oy6UwHXgZJg7hFXccUZRPYEj3/Iw7zx62K6ygFFTt5NDDgdkkTz8S3E3G9cgIod2EXv6Z3mbU9HXPvxQll30lBj3XpQqde5u8DGlmvmI9L4rYixj4ywVdvhTRRe/2mZKoaEJZQUDtYaI=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_5e5aaf50d9bf_key -iv $encrypted_5e5aaf50d9bf_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
