language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/toutatice.git"
  # REGISTRY_TOKEN
  secure: XvRJnShIUoaTZsHjrEW361avxdn3PRUKyrYtJB02hxx8RVFrcTJLoCzgHN3RYk+bU9ZUeYggaL0tZnt9MQn6LBEhktruzJChiMUxPSWnmdvCOtz8jw59UjCx4cVPAISsj0SDFHT6FQCbbG37lPo8w73szMLCukLztqEGGUNPjz3w0WgXAQ7YC15iMzhD+3Vvvp03EiOZFT/TINTFMp0IsMswHMkd/u68aoCf8TBLxMLd0cNczcCv96gPpUjZUCPsJg0F+f1VxKukEsIjfMBgS+XMAPg510Iyqd5+XGbcQp5WQgHsDzUNbtwCbkkAXyyOMaJIMCGJwFtiKMw6Qt6HRHmDfGVb+xVe8ddkZzlcsUR3eBiJKlIrJjdT7x43YdGYgxXV2fafVj4hxeKZDkcigJq5g6BeKOf6kl8BhykK/B9zJODCvDPoHHP+PD7CfGmBWyQxquuPVICvqjLYgzSP69sQ55EQx8jvgNP4+YL3sIEYCLIJKg2ErDvQcgwz23dkgpaq6v1ocSfe2eWHiGRqkopHYmWHakC1CfSd0ISQ70PwL/rwohVC3YXkb++ZpzqX2jRKK1a0kGq7o+Pmp9ZO/hsx3xmUy+HgEeb5sZI1Gte5TbdhIorEtxn1xE3jdsR7lihKDzWLA9cagvqiAyhCz657LjIcbznI5i/WnGhV+2I=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_5e5aaf50d9bf_key -iv $encrypted_5e5aaf50d9bf_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
